#!/usr/bin/env php
<?php

use League\CLImate\CLImate;
use REES46\ClickHouse\Logger;
use REES46\ClickHouse\Processor;
use Workerman\Worker;

define('APP_ROOT', __DIR__);
require APP_ROOT . '/vendor/autoload.php';
if (!class_exists('Composer\Autoload\ClassLoader', false)) {
	die(
		'You need to set up the project dependencies using the following commands:' . PHP_EOL .
		'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
		'php composer.phar install' . PHP_EOL
	);
}

$cli = new CLImate();
$cli->arguments->add([
	'log'     => [
		'prefix'       => 'l',
		'longPrefix'   => 'log',
		'description'  => 'Log file',
		'defaultValue' => APP_ROOT . '/log/clickhouse.log',
	],
	'log_level' => [
		'prefix'      => 'v',
		'longPrefix'  => 'log_level',
		'description' => 'Log level, available: ' . implode(', ', [Logger::TYPE_DEBUG, Logger::TYPE_INFO, Logger::TYPE_ERROR]),
		'defaultValue'=> Logger::TYPE_ERROR,
	],
	'help'    => [
		'prefix'      => 'h',
		'longPrefix'  => 'help',
		'description' => 'Prints a usage statement',
		'noValue'     => true,
	],
]);
$cli->arguments->parse();

if( $cli->arguments->get('help') ) {
	$cli->usage();
} else {
	//Читаем конфиги
	$config = parse_ini_file(APP_ROOT . '/config/secrets.ini', true);

	$worker = new Worker();
	$worker->onWorkerStart = function() use ($cli, $config) {
		$this->server = new Processor(new Logger($cli, $cli->arguments->get('log'), $cli->arguments->get('log_level')), $config);
	};
	$worker->count = $config['rabbit']['concurrency'];
	$worker->name = 'ClickHouse Queue';

	// run all workers
	Worker::runAll();
}
